[2024-12-26T11:05:49.966+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-26T11:05:49.977+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wiki_flow.extract_data_from_wikipedia manual__2024-12-26T11:05:47.815591+00:00 [queued]>
[2024-12-26T11:05:49.980+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wiki_flow.extract_data_from_wikipedia manual__2024-12-26T11:05:47.815591+00:00 [queued]>
[2024-12-26T11:05:49.981+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-26T11:05:49.986+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data_from_wikipedia> on 2024-12-26 11:05:47.815591+00:00
[2024-12-26T11:05:49.998+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=542) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-26T11:05:50.000+0000] {standard_task_runner.py:72} INFO - Started process 543 to run task
[2024-12-26T11:05:50.000+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'wiki_flow', 'extract_data_from_wikipedia', 'manual__2024-12-26T11:05:47.815591+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/testdatadownload.py', '--cfg-path', '/tmp/tmpod1h9emr']
[2024-12-26T11:05:50.001+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask extract_data_from_wikipedia
[2024-12-26T11:05:50.107+0000] {task_command.py:467} INFO - Running <TaskInstance: wiki_flow.extract_data_from_wikipedia manual__2024-12-26T11:05:47.815591+00:00 [running]> on host 1f987fbbf267
[2024-12-26T11:05:50.233+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gaurav' AIRFLOW_CTX_DAG_ID='wiki_flow' AIRFLOW_CTX_TASK_ID='extract_data_from_wikipedia' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T11:05:47.815591+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-26T11:05:47.815591+00:00'
[2024-12-26T11:05:50.237+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-26T11:05:50.237+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-26T11:05:50.237+0000] {logging_mixin.py:190} INFO - Current task name:extract_data_from_wikipedia state:running start_date:2024-12-26 11:05:49.977742+00:00
[2024-12-26T11:05:50.238+0000] {logging_mixin.py:190} INFO - Dag name:wiki_flow and current dag run status:running
[2024-12-26T11:05:50.238+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-26T11:05:50.242+0000] {logging_mixin.py:190} INFO - Getting wikipedia page... https://en.wikipedia.org/wiki/List_of_association_football_stadiums_by_capacity
[2024-12-26T11:05:50.478+0000] {logging_mixin.py:190} INFO - Html data is written in text file
[2024-12-26T11:05:50.479+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/testdatadownload.py", line 30, in extract_data_from_wiki
    with open('/opt/airflow/data/response_wiki.txt', 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/response_wiki.txt'
[2024-12-26T11:05:50.489+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-26T11:05:50.489+0000] {logging_mixin.py:190} INFO - Task start:2024-12-26 11:05:49.977742+00:00 end:2024-12-26 11:05:50.489457+00:00 duration:0.511715
[2024-12-26T11:05:50.490+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_data_from_wikipedia> dag:<DAG: wiki_flow> dagrun:<DagRun wiki_flow @ 2024-12-26 11:05:47.815591+00:00: manual__2024-12-26T11:05:47.815591+00:00, state:running, queued_at: 2024-12-26 11:05:47.879209+00:00. externally triggered: True>
[2024-12-26T11:05:50.490+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/opt/***/data/response_wiki.txt'
[2024-12-26T11:05:50.490+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=wiki_flow, task_id=extract_data_from_wikipedia, run_id=manual__2024-12-26T11:05:47.815591+00:00, execution_date=20241226T110547, start_date=20241226T110549, end_date=20241226T110550
[2024-12-26T11:05:50.496+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-26T11:05:50.497+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task extract_data_from_wikipedia ([Errno 2] No such file or directory: '/opt/airflow/data/response_wiki.txt'; 543)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/testdatadownload.py", line 30, in extract_data_from_wiki
    with open('/opt/airflow/data/response_wiki.txt', 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/response_wiki.txt'
[2024-12-26T11:05:50.519+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-26T11:05:50.534+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-26T11:05:50.535+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
